from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from domain.enums import AssetType, Exchange, OrderType


class AssetHolding(BaseModel):
    """
    Current holding in the portfolio.
    """

    model_config = ConfigDict(extra="ignore")

    name: str
    asset_type: AssetType
    quantity: float = Field(ge=0)
    average_price: float = Field(ge=0)

    last_price: float = Field(ge=0)

    invested_value: float = 0
    current_value: float = 0

    pnl: float = 0
    pnl_percent: float = 0

    @property
    def display_name(self) -> str:
        raise NotImplementedError
    
    @property
    def market_value(self) -> float:
        return self.quantity * self.last_price

    @property
    def cost_value(self) -> float:
        return self.quantity * self.average_price

class EquityHolding(AssetHolding):
    symbol: str
    asset_type: AssetType = AssetType.EQUITY
    exchange: Exchange
    isin: str | None = None
    sector: str | None = None

    @property
    def display_name(self) -> str:
        return self.symbol
    
class MutualFundHolding(AssetHolding):
    fund_name: str
    folio: str
    amfi_code: str | None = None
    xirr: float | None = None
    
    @property
    def display_name(self) -> str:
        return self.name
    
class Position(BaseModel):
    """
    Intraday/F&O position.
    """

    model_config = ConfigDict(extra="ignore")

    symbol: str

    quantity: float

    buy_price: float

    sell_price: float

    pnl: float


class Transaction(BaseModel):
    """
    Buy/Sell transaction.
    """

    model_config = ConfigDict(extra="ignore")

    order_id: str

    symbol: str

    order_type: OrderType

    quantity: float

    price: float

    order_date: datetime

class PerformanceMetrics(BaseModel):
    """
    Portfolio performance metrics.
    """

    annual_return: float = 0

    cagr: float = 0

    volatility: float = 0

    sharpe_ratio: float = 0

    sortino_ratio: float = 0

    beta: float = 0

    alpha: float = 0

    max_drawdown: float = 0

    information_ratio: float = 0

    calmar_ratio: float = 0

    treynor_ratio: float = 0

    xirr: Optional[float] = None


class Allocation(BaseModel):
    """
    Asset allocation.
    """

    category: str

    value: float

    percentage: float


class SectorAllocation(BaseModel):
    sector: str

    value: float

    percentage: float


class PortfolioSnapshot(BaseModel):
    """
    Future database model.

    We won't persist this yet, but when we
    introduce PostgreSQL later this model
    will already exist.
    """

    snapshot_date: date

    portfolio_value: float

    invested_value: float

    pnl: float


class AIInsight(BaseModel):
    """
    Output generated by the AI.
    """

    title: str

    summary: str

    recommendation: str

    confidence: float = Field(ge=0, le=1)